name: tom_md2pdf
description: Markdown to PDF converter using htmltopdfwidgets.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  htmltopdfwidgets: ^2.0.0
  path: ^1.9.0
  pdf: ^3.11.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  md2pdf: md_pdf_converter
