name: tom_build_cli
description: CLI implementation for the Tom build system.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  glob: ^2.1.2
  path: ^1.9.0
  yaml: ^3.1.2
  pub_semver: ^2.2.0
  
  # Tom packages
  tom_build:
    path: ../tom_build
  tom_d4rt:
  tom_core_kernel:
    path: ../../core/tom_core_kernel
  tom_core_server:
    path: ../../core/tom_core_server
  tom_dist_ledger:
    path: ../../xternal/tom_module_distributed/tom_dist_ledger
  tom_process_monitor:
    path: ../../xternal/tom_module_distributed/tom_process_monitor
  
  # Bridge package (for D4rt bridges)
  tom_dartscript_bridges:
    path: ../../dartscript/tom_dartscript_bridges
  tom_reflection_generator:
    path: ../../xternal/tom_module_reflection/tom_reflection_generator

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^6.0.0
  test: ^1.25.6
  tom_d4rt_generator:
  tom_build_kit:
    path: ../../xternal/tom_module_basics/tom_build_kit

