name: tom_build_cli
description: CLI implementation for the Tom build system.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  glob: ^2.1.2
  path: ^1.9.0
  yaml: ^3.1.2
  pub_semver: ^2.2.0
  
  # Tom packages
  tom_build:
    path: ../tom_build
  tom_d4rt:
  tom_core_kernel:
    path: ../../core/tom_core_kernel
  tom_core_server:
    path: ../../core/tom_core_server
  tom_dist_ledger:
    path: ../../distributed/tom_dist_ledger
  tom_process_monitor:
    path: ../../distributed/tom_process_monitor
  
  # D4rt CLI base (build CLI extends D4rt CLI)
  tom_d4rt_dcli:
  tom_vscode_scripting_api:
  tom_reflection_generator:
    path: ../../reflection/tom_reflection_generator

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^6.0.0
  test: ^1.25.6
  tom_d4rt_generator:
  tom_build_kit:
    path: ../tom_build_kit

