name: tom_build
description: Build tools and workspace analyzer for the Tom framework.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.3
  dart_style: ^3.0.0
  htmltopdfwidgets: ^2.0.0
  logging: ^1.3.0
  path: ^1.9.0
  pdf: ^3.11.3
  pub_semver: ^2.2.0
  tom_d4rt:
  tom_reflection: ^1.0.0
  tom_core_kernel:
    path: ../../core/tom_core_kernel
  tom_core_server:
    path: ../../core/tom_core_server
  tom_dist_ledger:
    path: ../../xternal/tom_module_distributed/tom_dist_ledger
  tom_process_monitor:
    path: ../../xternal/tom_module_distributed/tom_process_monitor
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.4
  tom_d4rt_generator:
  tom_reflection_generator:
    path: ../../xternal/tom_module_reflection/tom_reflection_generator
