name: tom_md2latex
description: Markdown to LaTeX converter with PDF output support.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  md2latex: md_latex_converter
